### ISSUE TITLE
ze_peak with ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE results in segfault

### ISSUE THREAD

**Issue by servesh** [oneapi-src/level-zero-tests#35]
Hi,

ze_peak with ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE  and set to explicit scaling results in segfault.

UMD: https://dgpu-docs.intel.com/releases/stable_736_25_20231031.html#sles-15sp4

```
$ ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE ./ze_peak -t sp_compute -v -x
Driver initialized
zeDriverGet...
Device count retrieved: 1
Device retrieved
Device Properties retrieved
Device :
 * name : Intel(R) Data Center GPU Max 1550
 * vendorId : 8086
 * deviceId : 0bd6
 * subdeviceId : 0
 * isSubdevice : FALSE
 * UUID : 00000000-0000-0000-ba22-f6e59d21eb92
 * coreClockRate : 1600

Device Compute Properties retrieved
Sub Device Count retrieved
Enable explicit scaling as we have sub devices inside root device
Sub Device Handles retrieved
The ordianl provided neither matches COMPUTE nor COPY engine, so disabling fixed dispatch
File path: ze_sp_compute.spv
Binary file length: 26332
Binary file loaded
Module created
splitting the total work items ::7516192768across subdevices ::2
Group size x: 1024
Group size y: 1
Group size z: 1
Group count x: 3670016
Group count y: 1
Group count z: 1
total work items that will be executed: 3758096384 requested: 3758096384
device input value allocated
device output buffer allocated
Input value copy encoded
Execution barrier appended
Command list closed
Command list enqueued
Command queue synchronized
Command list reset
Command list closed
Command list enqueued
Command queue synchronized
Command list reset
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Single Precision Compute (GFLOPS)
float : Group size set
current_sub_device_id value is ::0
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Segmentation fault

```

**Comment by servesh** [comment]
Please find the fix for this issue. It looks like the subdevice count is not being handled correctly.
```
diff --git a/perf_tests/ze_peak/src/ze_peak.cpp b/perf_tests/ze_peak/src/ze_peak.cpp
index b5d947e..e9e7ddc 100644
--- a/perf_tests/ze_peak/src/ze_peak.cpp
+++ b/perf_tests/ze_peak/src/ze_peak.cpp
@@ -897,6 +897,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
             synchronize_command_queue(context);
             current_sub_device_id++;
           }
+          current_sub_device_id = context.sub_device_count - 1;
         }
       } else {
         synchronize_command_queue(context);
@@ -914,6 +915,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
             synchronize_command_queue(context);
             current_sub_device_id++;
           }
+          current_sub_device_id = context.sub_device_count - 1;
         }
       } else {
         synchronize_command_queue(context);
@@ -1298,6 +1300,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
           synchronize_command_queue(context);
           current_sub_device_id++;
         }
+        current_sub_device_id = context.sub_device_count - 1;
       }
     } else {
       synchronize_command_queue(context);
@@ -1479,6 +1482,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
           synchronize_command_queue(context);
           current_sub_device_id++;
         }
+        current_sub_device_id = context.sub_device_count - 1;
       }
     } else {
       synchronize_command_queue(context);
@@ -1589,7 +1593,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
 
   if (reset_command_list) {
     if (context.sub_device_count) {
-      if (context.sub_device_count == current_sub_device_id) {
+      if (context.sub_device_count == current_sub_device_id + 1) {
         current_sub_device_id = 0;
         while (current_sub_device_id < context.sub_device_count) {
           context.reset_commandlist(context.cmd_list[current_sub_device_id]);
```

**Comment by eero-t** [comment]
@nrspruit Could somebody look at this? (and the other tickets filed for this project)

**Comment by Jemale** [comment]
This should be fixed now

**Comment by servesh** [comment]
@Jemale This issue is not fixed. Have you tested the patch you have proposed?

```
$ ZE_AFFINITY_MASK=0 ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE ./ze_peak -t sp_compute -v -x
Driver initialized
zeDriverGet...
Device count retrieved: 1
Device retrieved
Device Properties retrieved
Device :
 * name : Intel(R) Data Center GPU Max 1550
 * vendorId : 8086
 * deviceId : 0bd6
 * subdeviceId : 0
 * isSubdevice : FALSE
 * UUID : 00000000-0000-0000-ba22-f6e59d21eb92
 * coreClockRate : 1600

Device Compute Properties retrieved
Sub Device Count retrieved
Enable explicit scaling as we have sub devices inside root device
Sub Device Handles retrieved
The ordianl provided neither matches COMPUTE nor COPY engine, so disabling fixed dispatch
File path: ze_sp_compute.spv
Binary file length: 26332
Binary file loaded
Module created
splitting the total work items ::7516192768across subdevices ::2
Group size x: 1024
Group size y: 1
Group size z: 1
Group count x: 3670016
Group count y: 1
Group count z: 1
total work items that will be executed: 3758096384 requested: 3758096384
device input value allocated
device output buffer allocated
Input value copy encoded
Execution barrier appended
Command list closed
Command list enqueued
Command queue synchronized
Command list reset
Command list closed
Command list enqueued
Command queue synchronized
Command list reset
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Function created
Input buffer set as function argument
Output buffer set as function argument
Single Precision Compute (GFLOPS)
float : Group size set
current_sub_device_id value is ::0
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
XXXXXe+09 GFLOPS
float2 : Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
XXXXXe+09 GFLOPS
float4 : Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
XXXXXe+09 GFLOPS
float8 : Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
XXXXXe+09 GFLOPS
float16 : Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
XXXXXe+09 GFLOPS
compute_sp_v1 Function Destroyed
compute_sp_v2 Function Destroyed
compute_sp_v4 Function Destroyed
compute_sp_v8 Function Destroyed
compute_sp_v16 Function Destroyed
Input Buffer freed
Output Buffer freed
Module destroyed
<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Command queue destroyed
command_list destroyed
Context destroyed
```

Please notice the `current_sub_device_id value is` which is being set to 1 instead of both subdevices. Correct execution will look like this. The reported performance is also obviously wrong.

```
float : Group size set
current_sub_device_id value is ::0
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Command list reset
Command list reset
XXXX GFLOPS
float2 : Group size set
current_sub_device_id value is ::0
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Command list reset
Command list reset
XXXX GFLOPS
float4 : Group size set
current_sub_device_id value is ::0
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Command list reset
Command list reset
XXXX GFLOPS
float8 : Group size set
current_sub_device_id value is ::0
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Command list reset
Command list reset
XXXX GFLOPS
float16 : Group size set
current_sub_device_id value is ::0
Function launch appended
Command list closed
Group size set
current_sub_device_id value is ::1
Function launch appended
Command list closed
Command list reset
Command list reset
XXXX GFLOPS
compute_sp_v1 Function Destroyed
compute_sp_v2 Function Destroyed
compute_sp_v4 Function Destroyed
compute_sp_v8 Function Destroyed
compute_sp_v16 Function Destroyed
Input Buffer freed
Output Buffer freed
Module destroyed
<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Command queue destroyed
command_list destroyed
Context destroyed
```

The correct patch is still this,
```
diff --git a/perf_tests/ze_peak/src/ze_peak.cpp b/perf_tests/ze_peak/src/ze_peak.cpp
index 107848f..b7e8569 100644
--- a/perf_tests/ze_peak/src/ze_peak.cpp
+++ b/perf_tests/ze_peak/src/ze_peak.cpp
@@ -898,7 +898,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
             synchronize_command_queue(context);
             current_sub_device_id++;
           }
-          current_sub_device_id = 0;
+          current_sub_device_id = context.sub_device_count - 1;
         }
       } else {
         synchronize_command_queue(context);
@@ -916,7 +916,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
             synchronize_command_queue(context);
             current_sub_device_id++;
           }
-          current_sub_device_id = 0;
+          current_sub_device_id = context.sub_device_count - 1;
         }
       } else {
         synchronize_command_queue(context);
@@ -1071,7 +1071,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
             synchronize_command_queue(context);
             current_sub_device_id++;
           }
-          current_sub_device_id = 0;
+          current_sub_device_id = context.sub_device_count - 1;
         }
       } else {
         synchronize_command_queue(context);
@@ -1302,7 +1302,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
           synchronize_command_queue(context);
           current_sub_device_id++;
         }
-        current_sub_device_id = 0;
+        current_sub_device_id = context.sub_device_count - 1;
       }
     } else {
       synchronize_command_queue(context);
@@ -1484,7 +1484,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,
           synchronize_command_queue(context);
           current_sub_device_id++;
         }
-        current_sub_device_id = 0;
+        current_sub_device_id = context.sub_device_count - 1;
       }
     } else {
       synchronize_command_queue(context);
@@ -1595,7 +1595,7 @@ long double ZePeak::run_kernel(L0Context context, ze_kernel_handle_t &function,

   if (reset_command_list) {
     if (context.sub_device_count) {
-      if (context.sub_device_count == current_sub_device_id) {
+      if (context.sub_device_count == current_sub_device_id + 1) {
         current_sub_device_id = 0;
         while (current_sub_device_id < context.sub_device_count) {
           context.reset_commandlist(context.cmd_list[current_sub_device_id]);
```
